### ISSUE TITLE
Make it so that variables can be sent

### ISSUE THREAD

**Issue by Zetabaron** [Wendelstein7/DiscordHook-CC#1]
I want DiscordHook to be able to send variables so I can make an RF monitor on discord.

**Comment by superjaja05** [comment]
or just do hook.send(variable.."text") , `..` can merge strings and other stuff together into a string.

**Comment by Wendelstein7** [comment]
This issue is not in the scope of what DiscordHook does - you can use lua concatenation, like @superjaja05 said, to concatenate variables into strings. Or use `string.format(...)` (look up the lua docs)
